using System.Runtime.InteropServices;
using JavaNETInterface.Jni;

namespace JavaNETInterface.Jvmti;

[StructLayout(LayoutKind.Sequential)]
public unsafe struct JvmtiInterface1
{
    public void* Reserved1;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiEventMode, JvmtiEvent, JObject*, JvmtiError> SetEventNotificationMode;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int*, JObject***, JvmtiError> GetAllModules;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int*, JObject***, JvmtiError> GetAllThreads;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, JvmtiError> SuspendThread;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, JvmtiError> ResumeThread;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, JObject*, JvmtiError> StopThread;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, JvmtiError> InterruptThread;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, JvmtiThreadInfo*, JvmtiError> GetThreadInfo;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int*, JObject***, JvmtiError> GetOwnedMonitorInfo;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, JObject**, JvmtiError> GetCurrentContendedMonitor;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, void*, void*, int, JvmtiError> RunAgentThread;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int*, JObject***, JvmtiError> GetTopThreadGroups;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, JvmtiThreadGroupInfo*, JvmtiError> GetThreadGroupInfo;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int*, JObject***, int*, JObject***, JvmtiError> GetThreadGroupChildren;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int*, JvmtiError> GetFrameCount;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int*, JvmtiError> GetThreadState;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject**, JvmtiError> GetCurrentThread;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int, JMethodID**, long*, JvmtiError> GetFrameLocation;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int, JvmtiError> NotifyFramePop;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int, int, JObject**, JvmtiError> GetLocalObject;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int, int, int*, JvmtiError> GetLocalInt;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int, int, long*, JvmtiError> GetLocalLong;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int, int, float*, JvmtiError> GetLocalFloat;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int, int, double*, JvmtiError> GetLocalDouble;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int, int, JObject*, JvmtiError> SetLocalObject;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int, int, int, JvmtiError> SetLocalInt;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int, int, long, JvmtiError> SetLocalLong;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int, int, float, JvmtiError> SetLocalFloat;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int, int, double, JvmtiError> SetLocalDouble;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, byte*, JRawMonitorID**, JvmtiError> CreateRawMonitor;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JRawMonitorID*, JvmtiError> DestroyRawMonitor;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JRawMonitorID*, JvmtiError> RawMonitorEnter;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JRawMonitorID*, JvmtiError> RawMonitorExit;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JRawMonitorID*, long, JvmtiError> RawMonitorWait;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JRawMonitorID*, JvmtiError> RawMonitorNotify;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JRawMonitorID*, JvmtiError> RawMonitorNotifyAll;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JMethodID*, long, JvmtiError> SetBreakpoint;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JMethodID*, long, JvmtiError> ClearBreakpoint;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, byte*, JObject**, JvmtiError> GetNamedModule;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, JFieldID*, JvmtiError> SetFieldAccessWatch;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, JFieldID*, JvmtiError> ClearFieldAccessWatch;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, JFieldID*, JvmtiError> SetFieldModificationWatch;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, JFieldID*, JvmtiError> ClearFieldModificationWatch;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, byte*, JvmtiError> IsModifiableClass;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, long, byte**, JvmtiError> Allocate;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, byte*, JvmtiError> Deallocate;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, byte**, byte**, JvmtiError> GetClassSignature;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, int*, JvmtiError> GetClassStatus;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, byte**, JvmtiError> GetSourceFileName;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, int*, JvmtiError> GetClassModifiers;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, int*, JMethodID***, JvmtiError> GetClassMethods;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, int*, JFieldID***, JvmtiError> GetClassFields;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, int*, JClass***, JvmtiError> GetImplementedInterfaces;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, byte*, JvmtiError> IsInterface;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, byte*, JvmtiError> IsArrayClass;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, JObject**, JvmtiError> GetClassLoader;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int*, JvmtiError> GetObjectHashCode;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, JvmtiMonitorUsage*, JvmtiError> GetObjectMonitorUsage;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, JFieldID*, byte**, byte**, byte**, JvmtiError> GetFieldName;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, JFieldID*, JClass**, JvmtiError> GetFieldDeclaringClass;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, JFieldID*, int*, JvmtiError> GetFieldModifiers;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, JFieldID*, byte*, JvmtiError> IsFieldSynthetic;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JMethodID*, byte**, byte**, byte**, JvmtiError> GetMethodName;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JMethodID*, JClass**, JvmtiError> GetMethodDeclaringClass;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JMethodID*, int*, JvmtiError> GetMethodModifiers;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, JvmtiError> ClearAllFramePops;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JMethodID*, int*, JvmtiError> GetMaxLocals;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JMethodID*, int*, JvmtiError> GetArgumentsSize;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JMethodID*, int*, JvmtiLineNumberEntry**, JvmtiError> GetLineNumberTable;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JMethodID*, long*, long*, JvmtiError> GetMethodLocation;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JMethodID*, int*, JvmtiLocalVariableEntry**, JvmtiError> GetLocalVariableTable;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, byte*, JvmtiError> SetNativeMethodPrefix;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int, byte**, JvmtiError> SetNativeMethodPrefixes;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JMethodID*, int*, byte**, JvmtiError> GetBytecodes;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JMethodID*, byte*, JvmtiError> IsMethodNative;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JMethodID*, byte*, JvmtiError> IsMethodSynthetic;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int*, JClass***, JvmtiError> GetLoadedClasses;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int*, JClass***, JvmtiError> GetClassLoaderClasses;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, JvmtiError> PopFrame;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, JObject*, JvmtiError> ForceEarlyReturnObject;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int, JvmtiError> ForceEarlyReturnInt;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, long, JvmtiError> ForceEarlyReturnLong;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, float, JvmtiError> ForceEarlyReturnFloat;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, double, JvmtiError> ForceEarlyReturnDouble;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, JvmtiError> ForceEarlyReturnVoid;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int, JvmtiClassDefinition*, JvmtiError> RedefineClasses;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int*, JvmtiError> GetVersionNumber;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiCapabilities*, JvmtiError> GetCapabilities;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, byte**, JvmtiError> GetSourceDebugExtension;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JMethodID*, byte*, JvmtiError> IsMethodObsolete;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int, JObject**, JvmtiError*, JvmtiError> SuspendThreadList;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int, JObject**, JvmtiError*, JvmtiError> ResumeThreadList;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, JObject*, JvmtiError> AddModuleReads;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, byte*, JObject*, JvmtiError> AddModuleExports;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, byte*, JObject*, JvmtiError> AddModuleOpens;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, JClass*, JvmtiError> AddModuleUses;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, JClass*, JClass*, JvmtiError> AddModuleProvides;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, byte*, JvmtiError> IsModifiableModule;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int, JvmtiStackInfo**, int*, JvmtiError> GetAllStackTraces;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int, JObject**, int, JvmtiStackInfo**, JvmtiError> GetThreadListStackTraces;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, void**, JvmtiError> GetThreadLocalStorage;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, void*, JvmtiError> SetThreadLocalStorage;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int, int, JvmtiFrameInfo*, int*, JvmtiError> GetStackTrace;
    public void* Reserved105;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, long*, JvmtiError> GetTag;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, long, JvmtiError> SetTag;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiError> ForceGarbageCollection;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, void*, void*, JvmtiError> IterateOverObjectsReachableFromObject;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, void*, void*, void*, void*, JvmtiError> IterateOverReachableObjects;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiHeapObjectFilter, void*, void*, JvmtiError> IterateOverHeap;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, JvmtiHeapObjectFilter, void*, void*, JvmtiError> IterateOverInstancesOfClass;
    public void* Reserved113;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int, long*, int*, JObject***, long**, JvmtiError> GetObjectsWithTags;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int, JClass*, JObject*, JvmtiHeapCallbacks*, void*, JvmtiError> FollowReferences;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int, JClass*, JvmtiHeapCallbacks*, void*, JvmtiError> IterateThroughHeap;
    public void* Reserved117;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int, JObject**, JvmtiError> SuspendAllVirtualThreads;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int, JObject**, JvmtiError> ResumeAllVirtualThreads;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JniNativeInterface*, JvmtiError> SetJNIFunctionTable;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JniNativeInterface**, JvmtiError> GetJNIFunctionTable;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiEventCallbacks*, int, JvmtiError> SetEventCallbacks;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiEvent, JvmtiError> GenerateEvents;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int*, JvmtiExtensionFunctionInfo**, JvmtiError> GetExtensionFunctions;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int*, JvmtiExtensionEventInfo**, JvmtiError> GetExtensionEvents;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int, void*, JvmtiError> SetExtensionEventCallback;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiError> DisposeEnvironment;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiError, byte**, JvmtiError> GetErrorName;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiJlocationFormat*, JvmtiError> GetJLocationFormat;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int*, byte***, JvmtiError> GetSystemProperties;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, byte*, byte**, JvmtiError> GetSystemProperty;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, byte*, byte*, JvmtiError> SetSystemProperty;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiPhase*, JvmtiError> GetPhase;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiTimerInfo*, JvmtiError> GetCurrentThreadCpuTimerInfo;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, long*, JvmtiError> GetCurrentThreadCpuTime;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiTimerInfo*, JvmtiError> GetThreadCpuTimerInfo;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, long*, JvmtiError> GetThreadCpuTime;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiTimerInfo*, JvmtiError> GetTimerInfo;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, long*, JvmtiError> GetTime;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiCapabilities*, JvmtiError> GetPotentialCapabilities;
    public void* Reserved141;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiCapabilities*, JvmtiError> AddCapabilities;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiCapabilities*, JvmtiError> RelinquishCapabilities;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int*, JvmtiError> GetAvailableProcessors;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, int*, int*, JvmtiError> GetClassVersionNumbers;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JClass*, int*, int*, byte**, JvmtiError> GetConstantPool;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, void**, JvmtiError> GetEnvironmentLocalStorage;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, void*, JvmtiError> SetEnvironmentLocalStorage;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, byte*, JvmtiError> AddToBootstrapClassLoaderSearch;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JvmtiVerboseFlag, byte, JvmtiError> SetVerboseFlag;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, byte*, JvmtiError> AddToSystemClassLoaderSearch;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int, JClass**, JvmtiError> RetransformClasses;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int*, JvmtiMonitorStackDepthInfo**, JvmtiError> GetOwnedMonitorStackDepthInfo;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, long*, JvmtiError> GetObjectSize;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, JObject*, int, JObject**, JvmtiError> GetLocalInstance;
    public delegate* unmanaged[Cdecl]<JvmtiEnv*, int, JvmtiError> SetHeapSamplingInterval;
}