<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<PublishAot>true</PublishAot>
	<Platforms>x64;x86</Platforms>
	<NativeLib>Shared</NativeLib>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JavaNETInterface\JavaNETInterface.csproj" />
  </ItemGroup>

</Project>
