<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<IsAotCompatible>true</IsAotCompatible>
		<Platforms>x64</Platforms>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<Deterministic>true</Deterministic>
		<DeterministicSourcePaths>true</DeterministicSourcePaths>
	  </PropertyGroup>

	<PropertyGroup>
		<Title>JavaNETInterface</Title>
		<Description>JNI and JVMTI wrappers for C# NativeAOT</Description>
		<Authors>ST0PL</Authors>
		<PackageId>ST0PL.JavaNETInterface</PackageId>
		<Version>1.0.0</Version>
		<AssemblyVersion>1.0.0.0</AssemblyVersion>
		<FileVersion>1.0.0.0</FileVersion>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/ST0PL/JavaNETInterface</RepositoryUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Copyright>Copyright © 2026 ST0PL</Copyright>
		<PackageProjectUrl>https://github.com/ST0PL/JavaNETInterface</PackageProjectUrl>
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

</Project>
